GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Controllers/CategoryController.cs
using GalatasarayShop.Business.Services;
using GalatasarayShop.Data.Dto;
using GalatasarayShop.WebUI.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace GalatasarayShop.WebUI.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;


        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var categoryList = _categoryService.GetCategories();

            var ViewModel = categoryList.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description
            }).ToList();

            return View(ViewModel);
        }


        [HttpGet]
        public IActionResult New()
        {
            return View("Form", new CategoryFormViewModel());
        }

        [HttpPost]
        public IActionResult Save(CategoryFormViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", formData);
            }
            var categoryDto = new CategoryDto
            {
                Id = formData.Id,
                Name = formData.Name,
                Description = formData.Description
            };

            if (formData.Id == 0)
            {
                

                var response = _categoryService.AddCategory(categoryDto);

                if (response.IsSucceed)
                {
                    return RedirectToAction("Index");

                }
                else
                {
                    ViewBag.ErrorMessage = response.Message;
                    return View("form", formData);
                }
            }
            else
            {

                _categoryService.EditCategory(categoryDto);

                return RedirectToAction("Index");

            }









        }

        public IActionResult Edit(int id)
        {
            var category = _categoryService.GetCategoryById(id);

            var viewModel = new CategoryFormViewModel()
            {
                Id = category.Id,
                Name = category.Name,
                Description = category.Description
            };

            return View("Form" , viewModel);
        }

        public IActionResult Delete(int id)
        {
            _categoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }



       
    }
}

GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GalatasarayShop.WebUI.Areas.Admin.Controllers
{
   
    public class DashboardController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Controllers/ProductController.cs
using GalatasarayShop.Business.Services;
using GalatasarayShop.Data.Dto;
using GalatasarayShop.WebUI.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace GalatasarayShop.WebUI.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IWebHostEnvironment _environment;
        public ProductController(ICategoryService categoryService, IProductService productService, IWebHostEnvironment environment)
        {
            _categoryService = categoryService;
            _productService = productService;
            _environment = environment;
        }

        public IActionResult Index()
        {
            var products = _productService.GetProducts();

            var viewModel = products.Select(x => new ProductViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                UnitPrice = x.UnitPrice,
                UnitInStock = x.UnitInStock,
                CategoryId = x.CategoryId,
                ImagePath = x.ImagePath,
                CategoryName = x.CategoryName
            }).ToList();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult New()
        {
            var categories = _categoryService.GetCategories();
            ViewBag.Categories = categories;

            return View("form", new ProductFormViewModel());
        }

        [HttpPost]
        public IActionResult Save(ProductFormViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                var categories = _categoryService.GetCategories();
                ViewBag.Categories = categories;
                return View("form", formData);
            }
            var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };

            var allowedFileExtensions = new string[] { ".jpg", ".jpeg", ".png", ".jfif" };

            var fileContentType = formData.File.ContentType;

            var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(formData.File.FileName);

            var fileExtension = Path.GetExtension(formData.File.FileName);



            if (formData.File == null || formData.File.Length == 0 || !allowedFileContentTypes.Contains(fileContentType) || !allowedFileExtensions.Contains(fileExtension))
            {
                ModelState.AddModelError("file", "Lütfen jpg , jpeg, jfif veya png tipinde geçerli bir dosya yükleyiniz.");
                var categories = _categoryService.GetCategories();
                ViewBag.Categories = categories;
                return View("Form", formData);

            }







            var newFileName = fileNameWithoutExtension + "_" + Guid.NewGuid() + fileExtension;

            var folderPath = Path.Combine("images", "products");
            var wwwRootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);
            var wwwRootFilePath = Path.Combine(wwwRootFolderPath, newFileName);

            Directory.CreateDirectory(wwwRootFolderPath);

            using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
            {
                formData.File.CopyTo(fileStream);
            }

        
            if (formData.Id == 0)
            {
                var  productDto = new ProductDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    Description = formData.Description,
                    ImagePath = newFileName,
                    UnitPrice = formData.UnitPrice,
                    UnitInStock = formData.UnitInStock,
                    CategoryId = formData.CategoryId
                };

                var response = _productService.AddProduct(productDto);

                if (response.IsSucceed)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    var categories = _categoryService.GetCategories();
                    ViewBag.Categories = categories;

                    ViewBag.ErrorMessage = response.Message;
                    return View("form", formData);
                }
            }
            else
            {
               var productDto = new ProductDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    Description = formData.Description,
                    UnitPrice = formData.UnitPrice,
                    UnitInStock = formData.UnitInStock,
                    CategoryId = formData.CategoryId
                };

                if (formData.File != null)

                    productDto.ImagePath = newFileName;
                
                _productService.EditProduct(productDto);
            }
              
            return RedirectToAction("index");
        }

        public IActionResult Edit(int id)
        {
            var categories = _categoryService.GetCategories();
            ViewBag.Categories = categories;

            var product = _productService.GetProductById(id);

            var viewModel = new ProductFormViewModel()
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                UnitPrice = product.UnitPrice,
                UnitInStock = product.UnitInStock,
                CategoryId = product.CategoryId,
                //ImagePath = product.ImagePath,
            };
            ViewBag.Image = product.ImagePath;

            return View("form", viewModel);
        }

        public IActionResult Delete(int id)
        {
            _productService.DeleteProduct(id);

            return RedirectToAction("index");
        }

    }
}

GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Views/Shared/_CssPartial.cshtml
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.33/sweetalert2.min.css" integrity="sha512-doewDSLNwoD1ZCdA1D1LXbbdNlI4uZv7vICMrzxfshHmzzyFNhajLEgH/uigrbOi8ETIftUGBkyLnbyDOU5rpA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Views/Shared/_JsPartial.cshtml
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" integrity="sha512-k2GFCTbp9rQU412BStrcD/rlwv1PYec9SNrkbQlo6RZCf75l6KcC3UwDY8H5n5hl4v77IDtIPwOk9Dqjs/mMBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.33/sweetalert2.min.js" integrity="sha512-cYg5I1IgQJ3PudSiA/J3W15Q2zkgB+bbv7aKm0GuSvIineIx7jsSTc+iXGu0AyJOvdI6vWJkvJe97bVF3POQHA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
<html>

<head>
    <title>GalatasarayShop | </title>

  <partial name="_CssPartial"></partial>

    <style>
        label.required:after {
            content: "*\00a0";
            color: red;
            margin-left: 2px;
        }
    </style>

</head>

<body class="d-flex flex-column min-vh-100">
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none fw-bold">
                    GalatasarayShop YÖNETİM PANELİ
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ms-S5">
                    <li><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="nav-link px-2 text-white">Pano</a></li>
                    <li><a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link px-2 text-white">Kategoriler</a></li>
                    <li><a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link px-2 text-white">Ürünler</a></li>

                </ul>

                <div class="ms-3 text-white mt-1">
                    <a  asp-controller="Home" asp-action="Index" class="btn btn-warning">Galatasaray</a>
                </div>
              
            </div>
        </div>
    </header>

    @RenderBody()

    <footer class="py-5 bg-dark text-white text-center mt-3 mt-auto">
        ||GalatasarayShop
        <hr />
        <p class="text-secondary">Tüm hakları saklıdır.</p>
    </footer>

<partial name="_JsPartial"></partial>

    @await RenderSectionAsync("Scripts" , required: false)

    <script>
        $(document).ready(function() {
            $('.summernote').summernote(
                {
                    height:400
                }
            );
        });

    </script>

</body>
</html>