GalatasarayShop/GalatasarayShop.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GalatasarayShop.WebUI.Areas.Admin.Controllers
{
   
    public class DashboardController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GalatasarayShop/GalatasarayShop.WebUI/Controllers/AuthController.cs
using GalatasarayShop.Business.Services;
using GalatasarayShop.Data.Entities;
using GalatasarayShop.WebUI.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GalatasarayShop.WebUI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        public AuthController(IUserService userService)
        {
            _userService = userService;
        }


        [Route("Kayıt-Ol")]
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [Route("Kayıt-Ol")]
        [HttpPost]
        public IActionResult Register(RegisterViewModel formData)
        {

            if (!ModelState.IsValid)
            {
                return View(formData);
            }
            var user = new UserEntity
            {
                FirstName = formData.FirstName.Trim(),
                LastName = formData.LastName.Trim(),
                Email = formData.Email.Trim(),
                Password = formData.Password.Trim(),
                UserType = Data.Enums.UserTypeEnum.user


            };

            var response = _userService.AddUser(user);

            if (response.IsSucceed)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = response.Message;
                return View(formData);
            }






        }
        public async Task<IActionResult> Login(LoginViewModel formData)
        {
            var user = _userService.Login(formData.Email, formData.Password);

            if (user is null)
            {
                TempData["LoginMessage"] = "Kullanıcı adı veya şifreyi hatalı girdiniz!!";

                return RedirectToAction("Index", "Home");
            }
            var claims = new List<Claim>();

            claims.Add(new Claim("id", user.Id.ToString()));
            claims.Add(new Claim("firstName", user.FirstName));
            claims.Add(new Claim("lastName", user.LastName));
            claims.Add(new Claim("email", user.Email));
            claims.Add(new Claim("userType", user.UserType.ToString()));

            claims.Add(new Claim(ClaimTypes.Role, user.UserType.ToString()));

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(48))
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimIdentity),
                autProperties);

            return RedirectToAction("Index", "Home");


        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

GalatasarayShop/GalatasarayShop.WebUI/Views/Shared/_BannerPartial.cshtml
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Alışveriş Sitesi</h1>
        <p style="color:firebrick;font-weight:bold">Aldın Aldın.</p>
    </div>
</div>

GalatasarayShop/GalatasarayShop.WebUI/Views/Shared/_Layout.cshtml
<html>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

   

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   




    <style>
        label.required:after {
            content: "*\00a0";
            color: red;
            margin-left: 2px;
        }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none fw-bold">



                    <i style="color:red" class="bi bi-award-fill">GalatasarayShop</i>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ms-5">
                    <li><a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-white"><i style="color:gold" class="bi bi-house-heart">Ana Sayfa</i></a></li>
                    @* <li><a href="#" class="nav-link px-2 text-white">Features</a></li>*@

                </ul>

                @if (!User.IsLogged())
                {


                    <div id="login" class="d-none">
                        <partial name="_LoginPartial" model="new LoginViewModel()"></partial>
                    </div>
                    <div id="welcome" class="text-end">
                        <button id="btnGirisYap" type="button" class="btn btn-outline-light me-2"><i style="color:red" class="bi bi-box-arrow-in-right">Giriş</i></button>
                        <a asp-controller="Auth" asp-action="Register" class="btn btn-warning">Kayıt-Ol</a>
                    </div>

                }
                else
                {
                    var firstName = User.GetUserName();

                    var lastName = User.GetUserLastName();
                    <div class="d-flex">
                        <div style="color:red;font-weight:bold" class="mt-2"> Hoş Geldiniz @firstName @lastName </div>

                        @if (User.IsAdmin())
                        {
                            <div class="ms-3 text-white mt-1">
                                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="btn btn-danger">Yönetim Paneli</a>
                            </div>
                        }




                        <div class="ms-3 text-white mt-1">
                            <a asp-controller="Account" asp-action="Index" class="btn btn-outline-warning"><i class="bi bi-person-circle"></i> Profil Güncelle</a>

                        </div>

                        <div class="ms-3 text-white mt-1">
                            <a asp-controller="Auth" asp-action="Logout" class="btn btn-outline-warning"><i class="bi bi-box-arrow-left"></i> Çıkış-Yap</a>
                        </div>
                    </div>
                }



            </div>
        </div>
    </header>

    @RenderBody()


    <footer class="py-5 bg-dark text-white text-center mt-3 mt-auto">
        TR || GALATASARAYSHOP
        <hr />

        <p class="text-secondary">Tüm Hakları ÖzkanA.Ş Saklıdır</p>

    </footer>


    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" integrity="sha512-k2GFCTbp9rQU412BStrcD/rlwv1PYec9SNrkbQlo6RZCf75l6KcC3UwDY8H5n5hl4v77IDtIPwOk9Dqjs/mMBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <script>
        $('#btnGirisYap').click(function () {
            $('#welcome').addClass('d-none');
            $('#login').removeClass('d-none');
        })
    </script>
    <script>
        $('#btnGirisIptal').click(function () {
            $('#welcome').removeClass('d-none');
            $('#login').addClass('d-none');
        })

        @if (!string.IsNullOrWhiteSpace(TempData["LoginMessage"]?.ToString()))
        {
            @:toastr.error("@TempData["LoginMessage"].ToString()")
        }

        @if (!string.IsNullOrWhiteSpace(TempData["UpdateMessage"]?.ToString()))
        {
            @:toastr.success("@TempData["UpdateMessage"].ToString()");
        }


            lightbox.option({
                'resizeDuration': 200,
                'wrapAround': true,
                'maxWidth': 500,
                'maxHeight': 500

            })
    </script>

    
</body>
</html>